backbone: cond_unet
backbone_params:
  level_block: res
  in_channels: 3
  out_channels: 3
  cnn_depths: [64, 128, 256, 512]
  layers_per_block: 2 # 3 if using convNet
  filter_size: 3
  pooling_factor: 2
  residual: True
  dropout: 0.0
  norm: True