defaults:
  - _self_
  - model: att-gnn #graph-transformer
  - model/conv-layer@model.backbone_params: gat
  - model/size@model.backbone_params: large
  - legalizer@_here_: opt-adam
  - sc_placer@_here_: sgd
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

family: guided_diffusion
task: ibm-cluster512
num_classes: 10
method: debug_sc_placement
seed: 61
log_dir: logs/diffusion_debug
from_checkpoint: none
from_samples: ibm-cluster512.5_eval_cluster512.61

logger:
  filter: '.*'
  wandb: True
  wandb_entity: <your name here>
  wandb_project: <your project here>

# model params
implementation: custom
model:
  mask_key: is_ports
  use_mask_as_input: True
  max_diffusion_steps: 1000
  noise_schedule: linear
  t_encoding_type: sinusoid
  t_encoding_dim: 32
  beta_1: 1e-4
  beta_T: 0.02
  legality_guidance_weight: 4.0
  hpwl_guidance_weight: 0.008
  guidance_step: 1000
  forward_guidance_weight: 0.0 # For balancing forward and backward guidance
  grad_descent_steps: 10 # denoted m in universal guidance paper
  grad_descent_rate: 0.5
  self_recursion_steps: 10 # denoted k in universal guidance paper

# clustering params
cluster:
  clustered_samples: True # true if samples being loaded are clustered

# legalization
legalization:
  mode: none
  softmax_min: 5.0
  softmax_max: 50.0

# eval params
val_batch_size: 64
sc_halo: 1.0 # resize SC clusters
eval_samples: 0
eval_policy_algorithm: open_loop
eval_policy:
  num_iterations: 5
  num_clusters: 512
  sc_placement_algorithm: none # specify using sc_placer

show_intermediate_every: 200
num_output_samples: 18
train_data_limit: none
val_data_limit: none

hydra:
  output_subdir: null
  run:
    dir: .