family: continuous_diffusion
task: ibm
num_classes: 10
method: eval_rebuttal_v1-2_optopt_macro_20s_W16e-4_W12e-5_alr8e-3_t0_20k
seed: 400
log_dir: logs/diffusion_debug
from_checkpoint: v2_gmix1.6_2x.61.finetune_v2_gmix1.6_3M_cont_256_B3_b32_lr1e-4.91/step_250000.ckpt
param_sweep: false
logger:
  filter: .*
  wandb: true
  wandb_entity: 
  wandb_project: 
implementation: custom
model:
  mask_key: is_ports
  use_mask_as_input: true
  max_diffusion_steps: 1000
  noise_schedule: cosine
  t_encoding_type: sinusoid
  t_encoding_dim: 32
  beta_1: 0.0001
  beta_T: 0.02
  backbone: att_gnn
  backbone_params:
    edge_features: 4
    cond_node_features: 2
    hidden_size: 256
    hidden_node_features:
    - 256
    - 256
    - 256
    attention_node_features:
    - 256
    - 256
    - 256
    layers_per_block: 2
    input_encoding_dim: 32
    dropout: 0.0
    num_heads: 4
    mlp_num_layers: 2
    mlp_size_factor: 4
    ff_num_layers: 2
    ff_size_factor: 1
    att_implementation: flash
    dir_att_input: true
    conv_params:
      layer_type: gat
      heads: 4
      concat: true
    in_node_features: 2
    out_node_features: 2
    t_encoding_dim: 32
    device: cuda
    mask_key: is_ports
  guidance_mode: opt
  guidance_step: 1000
  forward_guidance_weight: 0.0
  grad_descent_rate: 0.008
  grad_descent_steps: 20
  hpwl_guidance_weight: 0.0016
  alpha_init: 0.0
  alpha_lr: 0.0005
  alpha_critical_factor: 0.5
  legality_potential_target: 0.0001
  use_adam: true
  legality_softmax_factor_min: 10.0
  legality_softmax_factor_max: 20.0
  legality_softmax_critical_factor: 0.1
  num_classes: 10
  input_shape:
  - 12752
  - 2
  device: cuda
cluster:
  is_cluster: false
  num_clusters: 512
  verbose: false
  cached_clusters: false
legalization:
  mode: opt
  softmax_min: 5.0
  softmax_max: 50.0
  step_size: 0.002
  grad_descent_steps: 20000
  save_videos: false
  save_timeseries: false
  softmax_critical_factor: 0.1
  hpwl_weight: 0.00012
  alpha_init: 1.0
  alpha_lr: 0.008
  legality_potential_target: 0
  use_adam: true
val_batch_size: 64
sc_halo: 1.0
macros_only: true
cached_macros: false
eval_samples: 0
eval_policy_algorithm: open_loop
eval_policy:
  num_iterations: 5
  num_clusters: 512
  sc_placement_algorithm: sgd
  verbose: false
  save_plots: false
  save_videos: false
  sc_placement_params:
    lr: 0.02
    grad_descent_steps: 128
    legality_guidance_weight: 0.0
    hpwl_guidance_weight: 1.0
    softmax_min: 5.0
    softmax_max: 50.0
edge_dropout: 0
scatter_plots:
- - lambda_2
  - legality_2
- - lambda_2
  - hpwl_ratio
- - hpwl_ratio
  - legality_2
- - original_hpwl_normalized
  - hpwl_normalized
show_intermediate_every: 200
num_output_samples: 18
train_data_limit: none
val_data_limit: none
num_params: 6285058
train_dataset: 0
val_dataset: 18
