legalization:
  mode: opt
  softmax_min: 5.0
  softmax_max: 50.0
  step_size: 2e-3
  grad_descent_steps: 5000
  save_videos: False
  save_timeseries: False
  softmax_critical_factor: 0.1
  hpwl_weight: 1e-5
  alpha_init: 1.0
  alpha_lr: 1e-3
  legality_potential_target: 1e-4
  use_adam: True