eval_policy:
  sc_placement_algorithm: adam_2stage
  sc_placement_params:
    step_size: 4e-3 # 2e-3 # 3e-3
    rearrangement_steps: 2000
    optimization_steps: 10000 # 5000 # 1000
    softmax_min: 5.0
    softmax_max: 50.0
    softmax_critical_factor: 0.05 # 0.1 # 0.2
    init_mode: use_placement
    hpwl_weight: 1e-5
    alpha_init: 0.0 # 1.0 # 2.0
    alpha_lr: 2e-5 # 1e-3 # 3e-3
    legality_potential_target: 1e-3
    legality_include_macros: True
    use_adam: True
    save_videos: False
    save_timeseries: False